name: Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - '*.*.x'

defaults:
  run:
    shell: bash -c "exec $CONDA_PREFIX/bin/bash -elo pipefail {0}"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3']
    env:
      PYTEST_ADDOPTS: --color=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: setup
        run: |
            # Don't install deps like this IRL, use setuptools.
            pip install pytest mypy flake8 coverage ruff

      - name: Style test (Flake8)
        run: flake8

      - name: Style test (Ruff)
        run: ruff check .

      - name: Type checking
        run: mypy .

      - name: Test
        run: pytest

    #   - name: Coverage report
    #     run: |
    #       coverage xml --ignore-errors
    #       coverage report
