name: Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - '*.*.x'

defaults:
  run:
    shell: bash -c "exec $CONDA_PREFIX/bin/bash -elo pipefail {0}"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3']
    env:
      PYTEST_ADDOPTS: --color=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: setup
        run: |
            # Don't install deps like this IRL, use setuptools.
            pip install pytest mypy flake8 coverage ruff pytest-cov

      - name: Style test (Flake8)
        run: flake8

      - name: Style test (Ruff)
        run: ruff check .

      - name: Type checking
        run: mypy .

      - name: Test
        run: pytest --cov

      - name: Coverage report
        run: |
          coverage html
          coverage report
          git config --global user.name 'GHA'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add --force htmlcov
          git commit -m "automated report"
          git push

    # See https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage
    #   - name: Codecov upload
    #     uses: codecov/codecov-action@v5
    #     with:
    #       name: ${{ github.workflow }}
    #       fail_ci_if_error: true
    #       verbose: true
    #       # Token not required for public repos, but avoids upload failure due
    #       # to rate-limiting (but not for PRs opened from forks)
    #       token: ${{ secrets.CODECOV_TOKEN }}
